name: Sync R1 to R2

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch (change to match your branch if necessary)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository R1
        uses: actions/checkout@v3

      - name: Set up Git for Repository R2
        run: |
          git config --global user.name "Piyush Agrawal"
          git config --global user.email "https.piyush@gmail.com"

      - name: Clone Repository R2
        run: |
          git clone https://github.com/Piyush-Fury/R2.git
          cd R2
          git checkout main  # Ensure you're on the right branch (change if needed)

      - name: Sync Changes from R1 to R2
        run: |
          # Copy files from R1 to R2 but avoid duplicating the R2 directory
          rsync -av --exclude='.git' $GITHUB_WORKSPACE/ R2/  # Copy contents of R1 to R2
          
          cd R2
          git add .
          git commit -m "Sync changes from R1 to R2"
          
          # Use the GitHub token for authentication
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Piyush-Fury/R2.git main
