#Hola amigo kese ho thik ho 
﻿apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  creationTimestamp: "2024-12-06T12:52:35Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/ebs-csi-aws-com
  name: pvc-1d2c27c5-9e73-4d3e-846e-372be590853b
  resourceVersion: "620552"
  uid: 3a0b8c42-6872-4dc0-8b36-dac6abd5368a
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-authentik-postgresql-0
    namespace: piyush
    resourceVersion: "620491"
    uid: 1d2c27c5-9e73-4d3e-846e-372be590853b
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1733483821927-8994-ebs.csi.aws.com
    volumeHandle: vol-0858e3e74d080d002
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - il-central-1c
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2024-12-06T12:52:35Z"
  phase: Bound
